### ISSUE TITLE
Blank window. Not usable

### ISSUE THREAD

**Issue by balwierz** [Bio7/bio7#5] opened 2019-03-28 17:31 UTC
Tested under Arch Linux 64bit and Debian Buster 64bit.

Application is unusable. Upon start it displays a splash screen and then displays a tiny window (couple of pixels in size) completely blank. You can resize the window but there is nothing in. Additionally console output in Debian shows:
```
WARNING: Unknown module: javafx.fxml specified to --add-opens
```
Under Arch there is no such error message.

Upon closing a java window pops up for a couple of seconds displaying error message
Title: "error saving preferences[unprintable non ascii character]NULL"
content: java.lang.nullPointerException

steps to reproduce:
unzip Bio7_3.0_lin64.zip
cd Bio7
./Bio7

**Comment by Bio7** [comment] 2019-03-28 18:07
I could think of the following scenarios:

You run Bio7 under Wayland which will not work (JavaFX will only run with X11 at the moment). So change to X11 or start the application with X11 if that is the case.

Another possible solution:
Try to launch Bio7 with the available Eclipse launcher binary (simply called Bio7 in the installation directory). Just a guess that some important Java arguments are ignored at Java startup.

The error message you cite is typically caused by JavaFX, the second error comes from the embedded
ImageJ plugin which want to save ImageJ preferences (can be ignored).

The error message indicates that the Java arguments especially for JavaFX  are not read correctly. Normally the launcher reads the Bio7.ini file to startup Java with all necessary arguments (there are now some extra for JavaFX and OpenJDK 12). Bio7 comes bundled with OpenJDK 12 and OpenJFX 12 (JavaFX). So this JDK should be started

In addition: Bio7 needs GTK 3 to run (Eclipse and JavaFX necessity).

**Comment by Bio7** [comment] 2019-03-28 18:12
Please note that ypu can open the Bio7.ini file with a normal texteditor to see the Java arguments.

Does Bio7 does not start at all? Normally it takes a while before the window opens from the described tiny window.

**Comment by balwierz** [comment] 2019-03-28 19:15
Thanks for suggestions.

1) Session type:
Arch: It is an X11 session
```
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=KDE
```
Debian: I am connecting via VNC to LXQt.
```
XDG_SESSION_TYPE=tty
XDG_CURRENT_DESKTOP=LXQt
```

2) Launch: I am launching via Bio7 binary. I removed --launcher.appendVmargs form Bio7.ini. No difference.

3) JavaFX: Under Debian I installed these packages libopenjfx-java, libopenjfx-jni, openjfx-source. It did not help. That is system java, so I guess does not apply to the bundled java but it would pull any dependencies if required.

4) I do have GTK3 (and Gnome3)

5) I put full path to the bundled java in Bio7.ini. No difference. Process details
```
/home/piotr/Bio7/jdk/bin/java -Xms1024m -Xmx4096m -Dprism.lcdtext=false -Dpython.console.encoding=UTF-8 -Dswt.enable.themedScrollBar=true --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --module-path=jdk/javafx/lib --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED -jar /home/piotr/Bio7//plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar -os linux -ws gtk -arch x86_64 -showsplash -launcher /home/piotr/Bio7/Bio7 -name Bio7 --launcher.library /home/piotr/Bio7//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016/eclipse_1801.so -startup /home/piotr/Bio7//plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar --launcher.overrideVmargs -exitdata 2238028 -clearPersistedState -vm /home/piotr/Bio7/jdk/bin/java -vmargs -Xms1024m -Xmx4096m -Dprism.lcdtext=false -Dpython.console.encoding=UTF-8 -Dswt.enable.themedScrollBar=true --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --module-path=jdk/javafx/lib --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.desktop/sun.awt=ALL-UNNAMED --add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED -jar /home/piotr/Bio7//plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
```


6) I waited 2 min after launch. The tiny window did not change. When I resize it, it remains blank. It is not using much CPU.

**Comment by Bio7** [comment] 2019-03-28 19:23
Please try to put the full OpenJDK path in the Bio7.ini save it and then start Bio7 with the Bio7 binary (not the command line)

**Comment by Bio7** [comment] 2019-03-28 19:38
The error: WARNING: Unknown module: javafx.fxml specified to --add-opens
indicates a wrong JDK somehow because the bundled OpenJDK embedds javafx in /jdk/javafx.

The path is also given in the Bio7.ini (the path should'nt be changed!)

**Comment by balwierz** [comment] 2019-03-28 19:43
I don't understand how this differ from what I have been doing so far. I have never been running it differently than ./Bio7. See (5) above. Ir must be reading the ini file since it gets all the options. java path is already absolute.

Or do you mean changing "--module-path" to a full path as well? I did that. Again no difference.

**Comment by Bio7** [comment] 2019-03-28 19:52
Do you see the all jar files in the folder jdk/javafx/lib? There you should see, e.g., javafx.fxml.jar

**Comment by balwierz** [comment] 2019-03-28 20:00
> By starting I mean not to use ./bio7 but instead using the Bio7 executable by clicking on it in the file explorer (started as executable)

No difference.


```
$ tree jdk/javafx/lib/
jdk/javafx/lib/
├── javafx-swt.jar
├── javafx.base.jar
├── javafx.controls.jar
├── javafx.fxml.jar
├── javafx.graphics.jar
├── javafx.media.jar
├── javafx.properties
├── javafx.swing.jar
├── javafx.web.jar
├── libavplugin-54.so
├── libavplugin-56.so
├── libavplugin-57.so
├── libavplugin-ffmpeg-56.so
├── libavplugin-ffmpeg-57.so
├── libdecora_sse.so
├── libfxplugins.so
├── libglass.so
├── libglassgtk2.so
├── libglassgtk3.so
├── libgstreamer-lite.so
├── libjavafx_font.so
├── libjavafx_font_freetype.so
├── libjavafx_font_pango.so
├── libjavafx_iio.so
├── libjfxmedia.so
├── libjfxwebkit.so
├── libprism_common.so
├── libprism_es2.so
├── libprism_sw.so
└── src.zip
```

**Comment by Bio7** [comment] 2019-03-28 20:34
Everything looks fine in that dir. Strange. In the past I had some problems with a correct formatted Bio7.ini file on Linux and you error suggests another problem. 

However it ran perfectly on Ubuntu 18.10 tested several times also with downloads fresh from sourceforge.

It is however strange that the javafx module can't be found by the Bio7 bundled openjdk on your system.

Which folders do you see in the Bio7 installation?

**Comment by balwierz** [comment] 2019-03-28 20:45
Yes, it looks fine for me as well. Given that the symptoms are the same on both systems I assume there is something wrong about the binary or with the bundled java.

The directories are:
```
configuration
features
jdk
p2
plugins
readme
```

**Comment by Bio7** [comment] 2019-03-28 20:53
Everything looks fine. I will have a look at it and retest it on other distributions on Monday (I'm travelling at the moment and have no access to a Linux OS)

**Comment by Bio7** [comment] 2019-03-28 21:42
Ok. A bit curious I just installed VirtualBox on a Mac and then installed Debian Stretch and downloaded Bio7 3.0 for Linux in Debian.

Bio7 is working as it should and starts up without any problem (also from the command line). 

Maybe you have a corrupt download?

**Comment by Bio7** [comment] 2019-03-28 22:23
Just one addition. I unzipped the folder in  /home/public (if read write access plays a role)

**Comment by balwierz** [comment] 2019-03-29 00:47
sha1sum of the zip I downloaded:
aa1b9a83af91fd34017d927d2396947f7e20539e

**Comment by Bio7** [comment] 2019-03-29 07:12
File on sourceforge is identical:
aa1b9a83af91fd34017d927d2396947f7e20539e

I can only think that the Bio7.ini arguments are causing this error. The default looks like this and works on Ubuntu and Debian:

-startup
plugins/org.eclipse.equinox.launcher_1.5.300.v20190213-1655.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.1000.v20190125-2016
-clearPersistedState
-vm
jdk/bin/java
--launcher.appendVmargs
-vmargs
-Xms1024m
-Xmx4096m
-Dprism.lcdtext=false
-Dpython.console.encoding=UTF-8
-Dswt.enable.themedScrollBar=true
--add-modules=ALL-SYSTEM
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--module-path=jdk/javafx/lib
--add-modules=javafx.controls,javafx.base,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web
--add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.java2d.opengl=ALL-UNNAMED
--add-opens=java.base/java.lang.invoke=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.desktop/java.awt.font=ALL-UNNAMED

What happens if you edit the file and delete everything to this line:

--add-modules=javafx.controls,javafx.base,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web

and then type the arguments (starting with --add-modules) one by one and inbetween test if you got different error messages.

Maybe there is a formatting problem on you system or the *.ini is corrupted.

**Comment by Bio7** [comment] 2019-03-29 08:11
Just installed Bio7 on Arch Linux (KDE) 2018.09.
It starts without problems.

**Comment by Bio7** [comment] 2019-04-04 11:28
It might be that there is a Linux JavaFX bug occuring only with HighDPI displays (scale factor 2 on Ubuntu - does not occur with scale factor 1). Are you using a HighDPI display?
I could make a built which disables the SceneBuilder for a test.

**Comment by balwierz** [comment] 2019-04-04 12:54
I have 3 fullHD monitors. Each of them has scaleDisplay=1.

After removing  "--add-modules=javafx.controls,javafx.base,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web" I am getting the same error messages

```
WARNING: Unknown module: javafx.fxml specified to --add-opens

(Bio7:21979): Gtk-WARNING **: 13:49:47.932: gtk_widget_size_allocate(): attempt to allocate widget with width -14 and height -64

(Bio7:21979): Gtk-WARNING **: 13:49:47.932: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
```

**Comment by Bio7** [comment] 2019-04-04 14:39
Very strange. It must been JavaFX somehow. You can try as vm arguments (with all default arguments):

`-Dprism.order=sw`

to use another renderer.

With 

`-Dprism.verbose=true`

you get some debug messages for JavaFX

**Comment by Bio7** [comment] 2019-04-04 15:04
I've uploaded a version which does not open the SceneBuilder perspective and changed some 2D views to use not the JavaFX Swing  impl.:

If the above arguments does not work try this version:

https://sourceforge.net/projects/bio7/files/bio7/Bio7%203.0/

Bio7_3.0_No_JavaFX_Default.zip

**Comment by balwierz** [comment] 2019-04-04 15:54
I tested the new No_JavaFX version and the same problem.

But I also managed to have a running Fedora 29 64bit installation. And it works under fedora. No warnings about JavaFX. The tiny windows expands after 2 seconds.

**Comment by Bio7** [comment] 2019-04-05 06:32
Maybe the problem on the other systems is an older GTK 3 version (I doubt this)?

It would be interesting what the differences are that the other two Linux
choke on the command line parameters for JavaFX. 

here an overview of the required GTK versions:

https://www.eclipse.org/swt/faq.php#gtkstartup

which is for Bio7 3.0 based on Eclipse/SWT 4.11.x: GTK+ 3.10.0 and its dependencies

**Comment by balwierz** [comment] 2019-04-05 18:30
gtk versions:
Arch: 3.24.7
Debian: 3.24.5
Fedora: 3.24.1

**Comment by Bio7** [comment] 2019-04-06 08:33
The only hint I have is the error you cited that the  javafx modules can't be found:

How does the full path name differ from Fedora?

What happens if you add a preceding slash: 

/path/to/javafx/lib

What happens when you export the path on the command line and change the *.ini:

export PATH_TO_FX=/path/to/javafx/lib

Replace in the *.ini file:

--module-path $PATH_TO_FX

**Comment by Bio7** [comment] 2019-04-17 14:00
I close this issue since I could not reproduce it on different Linux flavours.

**Closed by Bio7** 2019-04-17 14:00 UTC
